### PR TITLE
Implement zeroize for secret values

### LINKED ISSUE #5: Secret velues not erased
#### Summary

From the audit point BLS-02:

Secret values allocated to memory are not securely erased after going
out of scope. There is no perfect solution to consistently address that
issue, but the [zeroize](https://docs.rs/zeroize/latest/zeroize/) crate
is probably the best option out there. It's relatively easy to
integrate, by assigning the `Zeroize` trait, and is `no_std` like the
library.

### PR DESCRIPTION
**Pull request by moCello**
Resolves #5

### CODE REVIEW

**Comment by moCello** [comment]
This is a tricky situation because even when we implement `ZeroizeOnDrop` for `SecretKey`, the memory still won't be erased:

```rust
impl Zeroize for SecretKey {
    fn zeroize(&mut self) {
        self.0 = BlsScalar::zero();
    }
}

impl ZeroizeOnDrop for SecretKey {}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn zeroize() {
        let sk = SecretKey::from(BlsScalar::from(42));
        let ptr = sk.as_ref().0.as_ptr();
        drop(sk);

        // check that the memory is erased after the struct was dropped
        unsafe {
            let bytes = core::slice::from_raw_parts(ptr, 4);
            assert_eq!(bytes, [0; 4]);
        };
    }
}
```

As [this blogpost](https://benma.github.io/2020/10/16/rust-zeroize-move.html) describes this has to do with the memory being copied under the hood
> The answer is that in Rust, moving a value compiles into a memory copy in the general case. Sometimes, the compiler can be smart and optimize away a memory copy, but other times it is impossible. For example [..], in the manual drop() the value is moved into the drop() function, but the value is copied in memory while doing so.

The solution for this is to `Box` the `BlsScalar` in the `SecretKey`.

**Review by HDauven — APPROVED** [review]

**Review by herr-seppia — COMMENTED** [review]
Wasn't the issue about adding zeroize to secret data? 
Is there a reason to derive zeroize for public structure (like public key, apk etc)

**Comment by moCello** [comment]
> Wasn't the issue about adding zeroize to secret data? Is there a reason to derive zeroize for public structure (like public key, apk etc)

the issue was regarding secret values indeed. But while implementing I figured that it also doesn't hurt to implement it for other types as well.
Imagine for example someone being able to link a public key to a specific person because it has not been erased from a shared machine.

**Review by ureeves — APPROVED** [review]
I'm totally fine with introducing this and remove the `Copy` trait. I always found it strange that `SecretKey`s would be `Copy`. That said, while it does mitigate the problem, it doesn't solve it, since a move will produce the same results. It is, however, the best we can do for now.

**Comment by moCello** [comment]
In my opinion it doesn't make sense to have both the `Copy` and `Zerioze` traits on types where the user is responsible to make sure to erase the data locally before it goes out of scope.

I understand that removing the `Copy` on the public types (`PublicKey`, `APK`, `Signature`) simply as a precaution so we can add `Zeroize` might be overkill for now and can cause issues downstream. So I decided to implement `Zeroize` (and remove `Copy`) *only* for `SecretKey`.

If, at a later point, we decide that we need `Zeroize` on the other types too, we can still add it then.

**Review by herr-seppia — APPROVED** [review]
LGTM

**Pull request merged**
